---
# Configure your freshly installed software
- hosts: all
  roles:
  - role: osxc.repository
    clone_url: https://github.com/larssmit/iterm2-getafe.git
    dest: /Users/{{ ansible_user_id }}/src/github.com/larssmit/iterm2-getafe
  - role: homeshick
    castle_url: git@bitbucket.org:nettabo/dotfiles.git
  - role: neobundle
