---
# Here we describe every software we may want to install
- hosts: all
  vars:
    oh_my_zsh_theme: agnoster
  roles:
  - role: osxc.packages
    brew_taps:
    - caskroom/fonts
    - motemen/ghq
    - peco/peco
    brew_packages:
    - ghq
    - git
    - go
    - peco
    - tig
    - wget
    cask_packages:
    - alfred
    - atom
    - dropbox
    - font-sauce-code-powerline
    - iterm2
    - karabiner
  - role: hnakamur.oh-my-zsh
