---
# Here we describe every software we may want to install
- hosts: all
  roles:
  - role: osxc.packages
    brew_taps:
    - caskroom/fonts
    brew_packages:
    - git
    cask_packages:
    - font-sauce-code-powerline
    - iterm2
