---
# homeshick

- name: clone dotfiles
  command: /Users/{{ ansible_user_id }}/.homesick/repos/homeshick/bin/homeshick clone {{ castle_url }} creates=/Users/{{ ansible_user_id }}/.homesick/repos/dotfiles

- name: symlink dotfiles
  command: /Users/{{ ansible_user_id }}/.homesick/repos/homeshick/bin/homeshick link dotfiles
  register: homeshick_link_dotfiles
  changed_when: "'symlink' in homeshick_link_dotfiles.stdout"
